version: "3.7"
services:  

    mongo:
        image: mongo:6.0.4-jammy
        hostname: mongo
        user: root
        ports:
            - "27017:27017"
        networks:
            - default_net
        environment:
            MONGO_INITDB_DATABASE: stackoverflow
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./db/mongo/:/data/db
            - ./data/:/usr/local/share/
    
    mongo-express:
        image: mongo-express
        ports:
            - "8989:8181"
        networks:
            - default_net
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_OPTIONS_EDITORTHEME: dracula
    
    spark-master:
        image: bitnami/spark:3.3.1
        user: root
        hostname: spark
        networks:
            - default_net
        environment:
            SPARK_MODE: master
        ports:
            - "8181:8080"
        volumes:
            - ./spark/:/usr/local/share/

    spark-worker-1:
        image: bitnami/spark:3.3.1
        user: root
        networks:
            - default_net
        environment:
            SPARK_MODE: worker
            SPARK_MASTER_URL: spark://spark:7077
            SPARK_WORKER_MEMORY: 4G
            SPARK_WORKER_CORES: 1

networks:
    default_net:
